### ISSUE TITLE
Reproducibility of other baselines

### ISSUE THREAD

**Issue by kiddj** [NSIBF/NSIBF#1]
Thanks for your great work!

I just wonder how you reproduce the other baseline models' results.

I cannot reproduce the results of SWaT dataset in case of USAD.
(https://github.com/robustml-eurecom/usad)

Also, it seems that your paper has the exact same results as the USAD paeprs'.

**Comment by cfeng783** [comment]
Hi, we followed the tutorial in the repository and managed to get closed but slightly lower results as shown in the USAD paper after doing a hyperparameter search. To respect the result in the original paper, we use the same results in the paper for a fair comparison.
