### ISSUE TITLE
Related questions in bf_search

### ISSUE THREAD

**Issue by molly-sr** [NSIBF/NSIBF#2]
Hello,In bf_search I see that you have used _adjust_predicts function which has adjusted the predicted values based on the real values, I would like to ask what is the reason for this?

**Comment by molly-sr** [comment]
![image](https://user-images.githubusercontent.com/60607675/202062352-ab1a0317-de11-4a21-a294-61a7114ca5e5.png)

**Comment by cfeng783** [comment]
Hi, sorry that the highlighted annotation is misleading. A point is labelled as an anomaly if its score is "LARGER" than the threshold.

**Comment by cfeng783** [comment]
> Hello,In bf_search I see that you have used _adjust_predicts function which has adjusted the predicted values based on the real values, I would like to ask what is the reason for this?

Can you please specify which line of code?

**Comment by molly-sr** [comment]
for i in range(len(score)):
        if actual[i] and predict[i] and not anomaly_state:
                anomaly_state = True
                anomaly_count += 1
                for j in range(i, 0, -1):
                    if not actual[j]:
                        break
                    else:
                        if not predict[j]:
                            predict[j] = True
                            latency += 1
        elif not actual[i]:
            anomaly_state = False
        if anomaly_state:
            predict[i] = True
Thank you for your reply. I'm a little confused about this part of the code. I can't understand the reason for such adjustment？

**Comment by molly-sr** [comment]
Thank you for your reply. I'm a little confused about this part of the code. I can't understand the reason for such adjustment？I compared the evaluation indicators before and after the adjustment and found that they were quite different.

**Comment by molly-sr** [comment]
![image](https://user-images.githubusercontent.com/60607675/202116063-bdb365d9-6951-4f72-be14-252a25a073ca.png)

**Comment by cfeng783** [comment]
It's the implementation of the point-adjusted metrics for time series. You can find the details of the metrics in the following paper:

Haowen Xu, Wenxiao Chen, Nengwen Zhao, Zeyan Li, Jiahao Bu, Zhihan Li,
Ying Liu, Youjian Zhao, Dan Pei, Yang Feng, et al. 2018. Unsupervised anomaly
detection via variational auto-encoder for seasonal kpis in web applications. In
Proceedings of the 2018 World Wide Web Conference. 187–196

**Comment by molly-sr** [comment]
Thank you again for your reply,I will go to read these paper.
Another problem encountered in using：I use the 'th' calculated by bf_search as the threshold，and treated 'z_scores>th'  as an anomaly, the evaluation indexes such as recall and f1_score are calculated differently from the output results

**Comment by molly-sr** [comment]
Thank you again for your reply,I will go to read these paper.
